Repository TritonDataCenter/illumos-joyent, pull requests merged in 2020-07, with the labels that each got.

#316 LX: netlink errors have spurious flags
  usr/src/uts/common/brand/lx/io/lx_netlink.c
Labels: integration-approval

#315 isatty() should return ENOTTY if not a TTY
  usr/src/uts/common/brand/lx/syscall/lx_ioctl.c
Labels: integration-approval

#314 OS-8181 exposed fault in lx netlink bind/sendto
  usr/src/uts/common/brand/lx/io/lx_netlink.c
Labels: integration-approval

#281 OS-8196 Native zone support for link-local routes
  usr/src/cmd/svc/milestone/net-routing-setup
Labels: force-integration-approval, integration-approval

#319 OS-8197 log file closing can cause zoneadmd to crash
  usr/src/cmd/zoneadmd/log.c
Labels: integration-approval

#320 12830 Want centralized ksensor framework [fix name_to_major]
  usr/src/uts/intel/os/name_to_major
Labels: force-integration-approval
